# Generated by Django 2.2.1 on 2019-05-11 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('execution_instruction', models.CharField(max_length=200)),
                ('max_running', models.IntegerField(default=2)),
                ('time_limit', models.IntegerField(default=120, help_text='Maximum time in seconds application can run')),
                ('memory_limit', models.IntegerField(default=1024, help_text='Maximum memory in kilobytes application can use')),
                ('queue_limit', models.IntegerField(default=1000, help_text='Maximum number of entries in queue before rejecting new jobs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.IntegerField(choices=[(1, 'Queued'), (2, 'Cancelled'), (3, 'Executing'), (4, 'Success'), (5, 'Fail')], default=1)),
                ('job_input', models.TextField(blank=True)),
                ('job_output', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=10, help_text='Jobs with higher priority are executed first')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Application')),
            ],
            options={
                'ordering': ['priority', '-created'],
            },
        ),
    ]
