# Generated by Django 2.2.1 on 2019-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='executed',
            new_name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='execution_time',
            field=models.IntegerField(default=0, help_text='Seconds spent executing'),
        ),
        migrations.AddField(
            model_name='job',
            name='queue_time',
            field=models.IntegerField(default=0, help_text='Seconds spent queueing'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
