# Generated by Django 2.2.1 on 2019-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20190511_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='message_for_user',
            field=models.TextField(blank=True),
        ),
    ]
