# Generated by Django 2.2.1 on 2019-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_job_message_for_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['priority', 'queued']},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='created',
            new_name='queued',
        ),
        migrations.RemoveField(
            model_name='job',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='queue_time',
        ),
        migrations.AddField(
            model_name='job',
            name='execution_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='execution_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
