# Generated by Django 3.0.1 on 2019-12-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20190511_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='application',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
